name: Release zeP

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy_production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Zig
        run: |
          cd
          sudo apt install wget
          wget https://ziglang.org/download/0.14.0/zig-linux-x86_64-0.14.0.tar.xz
          tar xf zig-linux-x86_64-0.14.0.tar.xz
          sudo cp zig-linux-x86_64-0.14.0/zig /usr/local/bin
          sudo mv zig-linux-x86_64-0.14.0/lib /usr/local/bin/lib

      - name: Build Releases
        run: sh ./release.sh 0.1

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          tag: "0.1"
        run: |
          gh release create "$tag" ./release/**/* \
              --repo="$GITHUB_REPOSITORY" \
              --title="zep 0.1" \
              --generate-notes
